### PR TITLE
Require C++14

### PR DESCRIPTION
**Pull request by Expander**
When we switch from GM2Calc 1 to version 2 we can increase the required C++ standard, which has a few new nice features. This requirement is not dramatic concerning the required compilers (see diff), because C++14 is a minor upgrade compared to C++11.

I propose to upgrade to C++14, because these are the future minimum versions required by Eigen 4 and the boost libraries. In this way we would be forward-compatible.

### CODE REVIEW

**Comment by Expander** [comment]
What do you think?

**Comment by dhjjacob** [comment]
I don't have any problems with.  It runs on my home machine.

**Comment by Expander** [comment]
@dhjjacob thanks for your comment!
@pathron what is your opinion? Do you see any obstacles upgrading to C++14?

**Comment by pathron** [comment]
At this stage we should just do it, C++14 has been supported for long enough I think.

**Review by pathron — APPROVED** [review]

**Pull request merged**
